name: Build and Test

# This workflow will run on main branch and on any pull request targeting main
on:
  push:
    branches:
      - main
    tags: []
  pull_request:

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Check out code
        uses: actions/checkout@v4
      - name: Lint Go Code
        uses: golangci/golangci-lint-action@v6

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [golangci]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        run: go build -v ./...
