# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: |
       VERSION=${GITHUB_REF#refs/tags/}
       go build -ldflags "-X main.version=${VERSION}" -o dotty

    - name: Generate Changelog
      id: changelog
      run: |
        echo "## Changelog" > CHANGELOG.md
        git log --oneline $(git describe --tags --abbrev=0)..HEAD >> CHANGELOG.md
        echo "Changelog generated."

    - name: Create Release
      uses: softprops/action-gh-release@v2.2.1
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2.2.1
      with:
        tag_name: ${{ github.ref }}
        files: dotty
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
